version: '3.8'

services:
  crack-hash:
    build: .
    container_name: crack-hash-dev
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  cargo-cache: 